/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bryan_ndk_JniCallBack */

#ifndef _Included_com_bryan_ndk_JniCallBack
#define _Included_com_bryan_ndk_JniCallBack
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bryan_ndk_JniCallBack
 * Method:    nativeInitilize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_bryan_ndk_JniCallBack_nativeInitilize
  (JNIEnv *, jobject);

/*
 * Class:     com_bryan_ndk_JniCallBack
 * Method:    nativeThreadStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_bryan_ndk_JniCallBack_nativeThreadStart
  (JNIEnv *, jobject);

/*
 * Class:     com_bryan_ndk_JniCallBack
 * Method:    nativeThreadStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_bryan_ndk_JniCallBack_nativeThreadStop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
